services:
  frontend:
    build: ./Front-end
    ports:
      - "5173:5173"
    networks:
      - app-network

  backend:
    build: ./Back-end
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
